security:
    role_hierarchy:
            ROLE_SUPER_ADMIN: ROLE_ADMIN
            ROLE_ADMIN: ROLE_USER
            ROLE_CREATOR: ROLE_USER
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                always_remember_me: false
                token_provider:
                    doctrine: true
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: user_index
                always_use_default_target_path: true

            logout:
                path: app_logout
                target: public_index
            entry_point: 'form_login'
            custom_authenticator: App\Security\LoginAuthenticator
    access_control:
        - { path: ^/dashboard, role: ROLE_USER  }
        - { path: ^/login, role: PUBLIC_ACCESS }
        - { path: ^/teste, role: ROLE_USER }
        - { path: ^/contact, role: ROLE_USER } 
        - { path: ^/profile, role: ROLE_USER } 
        - { path: ^/admin, role: ROLE_ADMIN} 
        - { path: /, role: PUBLIC_ACCESS } 

        # - { path: ^/home, roles: [ROLE_ADMIN,ROLE_USER] } 

when@test:
    security:
        password_hashers:
            App\Entity\User: 'auto'
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
